name: CI-CD Pipeline

on:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        run: |
          IMAGE=rasikh111/myapp:${{ github.sha }}
          docker build -t $IMAGE .
          docker push $IMAGE
          echo "IMAGE=$IMAGE" >> $GITHUB_ENV

      - name: Update Kubernetes manifest
        run: |
          sed -i "s|image:.*|image: $IMAGE|g" k8s/deployment.yaml
          git config user.name "Muhammad Rasikh Riaz"
          git config user.email "mo.rasikhriaz@gmail.com"
          git add k8s/deployment.yaml
          git commit -m "Update image to $IMAGE"
          git push
